import json

import zcatalyst_sdk

from datastore import DatastoreService
from forecast import generate_forecast
from threshold import (
    should_generate_alert,
    generate_recommendation
)
from notifications import send_push, send_mail
from logger import info, error


def handler(context, basicio):

    try:

        info("Forecast Alert Job Started")

        app = zcatalyst_sdk.initialize()

        db = DatastoreService(app)

        info("Generating forecast...")
        forecast = generate_forecast(db)
        info("Forecast generated successfully")

        district_id = forecast["districtid"]

        info("Fetching historical baseline...")
        baseline = db.get_historical_baseline(district_id)
        info(f"Historical Baseline : {baseline}")

        prediction = float(forecast["predictedcrime"])
        risk = forecast["risklevel"]
        explanation = forecast.get("explanation", "")

        info(f"Explanation : {explanation}")
        info(f"Prediction : {prediction}")
        info(f"Risk : {risk}")

        if should_generate_alert(prediction):

            recommendation = generate_recommendation(risk)

            info("Before insert_early_warning")

            inserted = db.insert_early_warning(
                district_id=district_id,
                predicted_count=prediction,
                historical_baseline=baseline,
                risk_level=risk,
                recommendation=recommendation,
                shap_factors="Generated by QuickML",
                crime_subhead_id=0
            )

            info("After insert_early_warning")
            info(f"Inserted Row : {inserted}")

            alert = {
                "districtid": district_id,
                "predictedcount": prediction,
                "historicalbaseline": baseline,
                "risklevel": risk,
                "recommendation": recommendation
            }

            info("Before send_push")
            send_push(alert)
            info("After send_push")

            if risk == "CRITICAL":
                info("Before send_mail")
                send_mail(alert)
                info("After send_mail")

            basicio.write(json.dumps({
                "status": "ALERT GENERATED",
                "prediction": prediction,
                "risk": risk
            }))

        else:

            basicio.write(json.dumps({
                "status": "NO ALERT",
                "prediction": prediction,
                "risk": risk
            }))

        info("Forecast Alert Job Completed")

    except Exception as e:

        error(f"Exception Type: {type(e).__name__}")
        error(f"Exception Message: {str(e)}")

        basicio.write(json.dumps({
            "status": "ERROR",
            "message": str(e)
        }))

    finally:

        context.close()