import { useEffect, useRef, useState } from 'react'
import { GeoJSON, useMap } from 'react-leaflet'
// Karnataka district GIS (real, not placeholder). Imported as a URL so the file
// is emitted as a static asset and fetched on demand rather than inlined into
// the JS bundle. This is the size-reduced build (coordinates rounded to ~11 m,
// ~2.8 MB vs 6.5 MB) generated by scripts/simplify-geojson.mjs from the
// full-resolution source karnataka-districts.geojson; the dtname/dtcode11/
// Dist_LGD properties this component reads are preserved.
import districtsUrl from '../../assets/karnataka-districts.min.geojson?url'

// Literal hex — Leaflet SVG presentation attributes don't resolve CSS var().
const MAROON = '#4A1942'
const ACCENT_TINT = '#F1E4EF'
const FAINT_STROKE = 'rgba(255, 255, 255, 0.7)'

// Base = the pre-enhancement faint dashed outline, so the no-hover map stays
// pixel-comparable to the reference.
const BASE_STYLE = { fillOpacity: 0, fillColor: ACCENT_TINT, color: FAINT_STROKE, weight: 1.2, dashArray: '3 4' }
// Hovered district: translucent lavender fill + 2px solid maroon stroke.
const HOVER_STYLE = { fillOpacity: 0.35, fillColor: ACCENT_TINT, color: MAROON, weight: 2, dashArray: null }
// Non-hovered districts while another is hovered: dim with a translucent black
// fill. This sits in a pane UNDER the heatmap/markers (see below), so it dims
// only the base map, never the heat or hotspot markers.
const DIM_STYLE = { fillOpacity: 0.3, fillColor: '#000000', color: FAINT_STROKE, weight: 1.2, dashArray: '3 4' }
// Districts named by the active investigation stack (§4): accent outline so the
// chat's context is visible on the map without moving the viewport.
const HIGHLIGHT_STYLE = { fillOpacity: 0.18, fillColor: '#8E4B8C', color: '#8E4B8C', weight: 2, dashArray: null }

function districtIdOf(props = {}) {
  return props.dtcode11 ?? props.Dist_LGD ?? props.dtname
}
function districtNameOf(props = {}) {
  return props.dtname ?? 'Unknown district'
}
// Loose match so slot values like "Bengaluru Urban" line up with GIS "dtname".
function normDistrict(name) {
  return String(name || '')
    .toLowerCase()
    .replace(/\b(urban|rural|district)\b/g, '')
    .replace(/[^a-z]/g, '')
}

export default function DistrictOutlines({ onDistrictHover, onDistrictClick, pinnedId = null, interactive = true, highlightDistricts = [] }) {
  const map = useMap()
  const groupRef = useRef(null)
  const pinnedIdRef = useRef(pinnedId)
  const highlightRef = useRef(new Set())
  const [geojson, setGeojson] = useState(null)

  pinnedIdRef.current = pinnedId
  highlightRef.current = new Set(highlightDistricts.map(normDistrict).filter(Boolean))

  // Dedicated pane BELOW the overlay pane (heat canvas + hotspot markers live at
  // z-index 400). Keeping districts here means the dim-others fill can never
  // darken the heatmap or markers — they always render on top.
  useEffect(() => {
    if (!map.getPane('districts')) {
      map.createPane('districts')
      map.getPane('districts').style.zIndex = '350'
    }
  }, [map])

  useEffect(() => {
    let alive = true
    fetch(districtsUrl)
      .then((r) => {
        // A 404 from Catalyst's gateway still carries a well-formed JSON body
        // (`{status:'failure', …}`), so `r.json()` resolves happily and Leaflet
        // then throws "Invalid GeoJSON object." out of render — blanking the
        // whole app. Reject on the status, and again on anything that is not a
        // FeatureCollection, so a missing asset degrades to "no outlines".
        if (!r.ok) throw new Error(`districts geojson: HTTP ${r.status}`)
        return r.json()
      })
      .then((data) => {
        if (!data || data.type !== 'FeatureCollection' || !Array.isArray(data.features)) {
          throw new Error('districts geojson: not a FeatureCollection')
        }
        if (alive) setGeojson(data)
      })
      .catch((err) => {
        // Silent on screen (the map still works without boundaries) but never
        // silent in the console — a 404 here means the asset is not being served.
        console.error('[DistrictOutlines]', err)
        if (alive) setGeojson(null)
      })
    return () => {
      alive = false
    }
  }, [])

  // Re-apply the pinned district's highlight when styles reset, so a clicked
  // district stays highlighted after the mouse leaves it.
  const resetAll = () => {
    groupRef.current?.eachLayer((l) => {
      const props = l.feature?.properties
      const id = districtIdOf(props)
      if (id != null && id === pinnedIdRef.current) {
        l.setStyle(HOVER_STYLE)
      } else if (highlightRef.current.has(normDistrict(districtNameOf(props)))) {
        l.setStyle(HIGHLIGHT_STYLE)
      } else {
        l.setStyle(BASE_STYLE)
      }
    })
  }

  // Reflect pin/highlight changes (card close, new investigation context) onto styles.
  useEffect(() => {
    resetAll()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pinnedId, highlightDistricts])

  const onEachFeature = (feature, layer) => {
    if (!interactive) return
    const props = feature.properties || {}
    const id = districtIdOf(props)
    const name = districtNameOf(props)

    layer.on('mouseover', () => {
      groupRef.current?.eachLayer((l) => l.setStyle(l === layer ? HOVER_STYLE : DIM_STYLE))
      layer.bringToFront()
      onDistrictHover?.(id, name)
    })
    layer.on('mouseout', () => {
      resetAll()
    })
    layer.on('click', () => {
      map.fitBounds(layer.getBounds(), { padding: [40, 40] })
      onDistrictClick?.(id, name)
    })
  }

  if (!geojson) return null

  return (
    <GeoJSON
      ref={groupRef}
      data={geojson}
      pane="districts"
      style={() => BASE_STYLE}
      onEachFeature={onEachFeature}
    />
  )
}
