/**
 * scratch/verify_ml_endpoints.mjs
 *
 * Proves POST /predict/forecast and POST /query speak the ACTUAL QuickML
 * contracts, not the invented ones the code used to assume.
 *
 * Emulated from the provisioned endpoints:
 *   forecast  POST .../endpoints/predict
 *             { data: { casemaster__crimeregistereddate: "YYYY-MM-DD" } }
 *             -> { result: { "YYYY-MM-DD": <number> } }
 *             auth: X-QUICKML-ENDPOINT-KEY only
 *   rag       POST .../rag/answer
 *             { query: "..." } -> { answer: "..." }
 *
 * `fetch` is stubbed, so nothing leaves the machine and the real endpoint key is
 * never used. Asserts on the OUTBOUND request too — a response-only test would
 * pass while sending a malformed body.
 *
 * Run:  node scratch/verify_ml_endpoints.mjs     (from functions/scrb-backend)
 * Exit: 0 = all pass.
 */

import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const catalyst = require('zcatalyst-sdk-node');

// Keep the genuine fetch for driving the local server — the stub below replaces
// the global one that the services use.
const realFetch = globalThis.fetch.bind(globalThis);

// --- capture every outbound call -------------------------------------------
const calls = [];
let forecastPerDate = 3; // predicted count the fake model returns per date
let ragAnswer = 'Based on the uploaded crime records, theft is the most common category.';
let forceStatus = null;

globalThis.fetch = async (url, init = {}) => {
  const body = init.body ? JSON.parse(init.body) : null;
  calls.push({ url: String(url), headers: init.headers ?? {}, body });

  if (forceStatus) {
    return {
      ok: false,
      status: forceStatus,
      text: async () => 'stubbed failure',
      json: async () => ({}),
    };
  }

  if (String(url).includes('/endpoints/predict')) {
    const date = body?.data?.casemaster__crimeregistereddate;
    return { ok: true, status: 200, json: async () => ({ result: { [date]: forecastPerDate } }) };
  }
  if (String(url).includes('/rag/answer')) {
    return { ok: true, status: 200, json: async () => ({ answer: ragAnswer }) };
  }
  return { ok: false, status: 404, text: async () => 'unexpected url', json: async () => ({}) };
};

// --- Catalyst stub ----------------------------------------------------------
let CURRENT_ROLE = 'Analyst';
const EARLY_WARNINGS = [
  { ROWID: '1', districtid: 26, crimesubheadid: 0, predictedcount: 45, historicalbaseline: 30,
    risklevel: 'CRITICAL', recommendation: 'Increase police patrol in predicted hotspot.',
    generatedat: '2026-07-26 10:00:00', shaptopfactors: 'Generated by QuickML' },
  { ROWID: '2', districtid: 29, crimesubheadid: 7, predictedcount: 12, historicalbaseline: 20,
    risklevel: 'MEDIUM', recommendation: 'Monitor.', generatedat: '2026-07-25 10:00:00',
    shaptopfactors: null },
];
const DISTRICTS = [
  { districtid: 26, districtname: 'Bengaluru Urban' },
  { districtid: 29, districtname: 'Mysuru' },
];
const CRIMESUBHEADS = [{ crimesubheadid: 7, crimesubheadname: 'House Theft' }];
const zcqlLog = [];

function zcqlRoute(q) {
  zcqlLog.push(String(q));
  if (/FROM\s+earlywarnings/i.test(q)) {
    let rows = EARLY_WARNINGS;
    const m = /districtid\s*=\s*'([^']+)'/i.exec(q);
    if (m) rows = rows.filter((r) => String(r.districtid) === m[1]);
    return rows.map((r) => ({ earlywarnings: r }));
  }
  if (/FROM\s+district\b/i.test(q)) return DISTRICTS.map((r) => ({ district: r }));
  if (/FROM\s+crimesubhead\b/i.test(q)) return CRIMESUBHEADS.map((r) => ({ crimesubhead: r }));
  return [];
}

const stubApp = {
  zcql: () => ({ executeZCQLQuery: async (q) => zcqlRoute(q) }),
  userManagement: () => ({
    getCurrentUser: async () => ({
      user_id: 'user-test-001',
      zuid: 'zuid-test-001',
      email_id: 'tester@example.com',
      role_details: { role_id: 'r1', role_name: CURRENT_ROLE },
    }),
  }),
  datastore: () => ({ table: () => ({ insertRow: async (r) => r, getPagedRows: async () => ({ data: [] }) }) }),
  cache: () => ({ segment: () => ({ get: async () => null, put: async () => null }) }),
  quickML: () => ({ model: () => ({ predict: async () => ({}) }) }),
};
catalyst.initialize = () => stubApp;

const { default: app } = await import('../index.js');
const server = app.listen(0);
await new Promise((r) => server.once('listening', r));
const base = `http://127.0.0.1:${server.address().port}`;

async function hit(method, path, body) {
  const r = await realFetch(base + path, {
    method,
    headers: body ? { 'Content-Type': 'application/json' } : {},
    body: body ? JSON.stringify(body) : undefined,
  });
  let json = null;
  try {
    json = await r.json();
  } catch {
    json = null;
  }
  return { status: r.status, body: json };
}

const checks = [];
let failures = 0;
function check(label, passed, detail = '') {
  if (!passed) failures++;
  checks.push(`${passed ? 'PASS' : 'FAIL'}  ${label}${detail ? ` — ${detail}` : ''}`);
}

// =========================== forecast ======================================
calls.length = 0;
let res = await hit('POST', '/predict/forecast', { district: 'Bengaluru', crime_type: 'theft', window_days: 30 });
const fc = res.body?.data;

check('POST /predict/forecast returns 200', res.status === 200, `status=${res.status}`);
check(
  'sums the window rather than reporting one day',
  fc?.predictedCount === 30 * forecastPerDate,
  `predictedCount=${fc?.predictedCount} (want ${30 * forecastPerDate} = 30 days x ${forecastPerDate})`,
);
check('one prediction call per day in the window', calls.length === 30, `calls=${calls.length}`);
check(
  'every call carries the X-QUICKML-ENDPOINT-KEY header',
  calls.every((c) => 'X-QUICKML-ENDPOINT-KEY' in c.headers),
  `first=${JSON.stringify(Object.keys(calls[0]?.headers ?? {}))}`,
);
check(
  'no Bearer/oauth header is sent to the forecast endpoint',
  calls.every((c) => !('Authorization' in c.headers)),
);
check(
  'body shape is { data: { casemaster__crimeregistereddate } }',
  calls.every((c) => typeof c.body?.data?.casemaster__crimeregistereddate === 'string'),
  `first body=${JSON.stringify(calls[0]?.body)}`,
);
const dates = calls.map((c) => c.body.data.casemaster__crimeregistereddate);
check('dates are distinct and ISO yyyy-mm-dd', new Set(dates).size === 30 && dates.every((d) => /^\d{4}-\d{2}-\d{2}$/.test(d)), `sample=${dates.slice(0, 3).join(', ')}`);
check('dates are in the FUTURE (window starts tomorrow)', dates.every((d) => d > new Date().toISOString().slice(0, 10)), `min=${dates.slice().sort()[0]}`);
check('riskLevel derived from the total', fc?.riskLevel === 'CRITICAL', `riskLevel=${fc?.riskLevel} for count=${fc?.predictedCount}`);
check(
  'filtersApplied is false — the model has no district/crime-type input',
  fc?.filtersApplied === false,
  `filtersApplied=${fc?.filtersApplied} modelInputs=${JSON.stringify(fc?.modelInputs)}`,
);
check('district and crimeType are echoed for labelling', fc?.district === 'Bengaluru' && fc?.crimeType === 'theft');

// long window must not fan out unbounded
calls.length = 0;
res = await hit('POST', '/predict/forecast', { district: 'D', crime_type: 'theft', window_days: 365 });
check('a 365-day window is sampled, not 365 calls', calls.length <= 31, `calls=${calls.length}`);
check('sampled window is flagged and scaled up', res.body?.data?.sampled === true && res.body?.data?.predictedCount > 900, `sampled=${res.body?.data?.sampled} count=${res.body?.data?.predictedCount}`);

// "unknown" must not render as a confident zero
calls.length = 0;
forecastPerDate = null;
res = await hit('POST', '/predict/forecast', { district: 'D', crime_type: 'theft', window_days: 7 });
check('unreadable model output yields null, not 0', res.body?.data?.predictedCount === null, `predictedCount=${res.body?.data?.predictedCount}`);
forecastPerDate = 3;

// endpoint failure should not read as our bug
forceStatus = 500;
res = await hit('POST', '/predict/forecast', { district: 'D', crime_type: 'theft', window_days: 7 });
check('upstream 500 surfaces as 500, not a fake success', res.status === 500 && res.body?.success === false, `status=${res.status}`);
forceStatus = null;

res = await hit('POST', '/predict/forecast', {});
check('empty body rejected with 400', res.status === 400, `status=${res.status}`);

// =========================== chat / RAG ====================================
CURRENT_ROLE = 'Investigator';
calls.length = 0;
res = await hit('POST', '/query', { session_id: 's1', query: 'How many thefts were reported in zone 5 in 2024?' });

check('POST /query returns 200', res.status === 200, `status=${res.status}`);
check('answer comes from the RAG endpoint', res.body?.data?.answer === ragAnswer, `answer=${JSON.stringify(res.body?.data?.answer)?.slice(0, 60)}`);
const ragCalls = calls.filter((c) => c.url.includes('/rag/answer'));
check('exactly ONE RAG call — intent extraction is local, not a round-trip', ragCalls.length === 1, `ragCalls=${ragCalls.length}`);
check('RAG body is { query } only', ragCalls[0] && Object.keys(ragCalls[0].body).length === 1 && typeof ragCalls[0].body.query === 'string', `keys=${JSON.stringify(Object.keys(ragCalls[0]?.body ?? {}))}`);
check(
  'no invented fields are sent (vector_store_id / model / task)',
  ragCalls[0] && !('vector_store_id' in ragCalls[0].body) && !('model' in ragCalls[0].body) && !('task' in ragCalls[0].body),
);
check('URL is the complete /rag/answer path, not base + /v1/rag/query', ragCalls[0]?.url.endsWith('/rag/answer'), `url=${ragCalls[0]?.url}`);
check('intent classified locally', res.body?.data?.intent === 'aggregate_stats', `intent=${res.body?.data?.intent}`);
check('entities extracted locally', res.body?.data?.entities?.zone === '5' && res.body?.data?.entities?.year === '2024' && res.body?.data?.entities?.crimeType === 'theft', `entities=${JSON.stringify(res.body?.data?.entities)}`);

// intent routing spread
const INTENT_CASES = [
  ['Show me the network of accomplices for ACC-1', 'network_lookup'],
  ['What is the behavioural profile of this accused?', 'profile_lookup'],
  ['Forecast thefts for next 30 days', 'forecast'],
  ['Where are the crime hotspots in Bengaluru?', 'hotspot_lookup'],
  ['Generate a report of last month', 'report_generate'],
  ['Details for case CR-2024-114', 'search_records'],
  ['qwertyuiop', 'search_records'],
];
for (const [q, want] of INTENT_CASES) {
  const r = await hit('POST', '/query', { session_id: 's1', query: q });
  check(`intent: "${q.slice(0, 34)}"`, r.body?.data?.intent === want, `got=${r.body?.data?.intent} want=${want}`);
}

res = await hit('POST', '/query', { session_id: 's1' });
check('missing query rejected with 400', res.status === 400, `status=${res.status}`);


// =========================== alerts ========================================
CURRENT_ROLE = 'Policymaker';
zcqlLog.length = 0;
res = await hit('GET', '/alerts/active');
const list = res.body?.data;

check('GET /alerts/active returns 200', res.status === 200, `status=${res.status}`);
check('reads earlywarnings, NOT the nonexistent Alerts table',
  zcqlLog.some((q) => /FROM\s+earlywarnings/i.test(q)) && !zcqlLog.some((q) => /FROM\s+Alerts\b/i.test(q)),
  `queries=${zcqlLog.length}`);
check('returns the fixture alerts', Array.isArray(list) && list.length === 2, `n=${list?.length}`);
check('newest first (ORDER BY generatedat DESC)', /ORDER BY generatedat DESC/i.test(zcqlLog[0] ?? ''),
  (zcqlLog[0] ?? '').replace(/\s+/g, ' ').slice(0, 64));
check('every field AlertCard reads is present',
  list?.every((a) => ['id','title','description','district','crimeType','severity','detectedAt'].every((k) => k in a)),
  `keys=${Object.keys(list?.[0] ?? {}).join(',')}`);
check('CRITICAL collapses to severity "high" (the only 3 the SPA styles)',
  list?.[0]?.severity === 'high', `severity=${list?.[0]?.severity}`);
check('...but the true CRITICAL level is preserved', list?.[0]?.riskLevel === 'CRITICAL', `riskLevel=${list?.[0]?.riskLevel}`);
check('MEDIUM maps to "medium"', list?.[1]?.severity === 'medium', `severity=${list?.[1]?.severity}`);
check('severity is always one the SPA can style', list?.every((a) => ['high','medium','low'].includes(a.severity)));
check('districtid resolved to a name', list?.[0]?.district === 'Bengaluru Urban', `district=${list?.[0]?.district}`);
check('district names resolved in ONE query, not per row',
  zcqlLog.filter((q) => /FROM\s+district\b/i.test(q)).length === 1,
  `districtQueries=${zcqlLog.filter((q) => /FROM\s+district\b/i.test(q)).length}`);
check('crimesubheadid 0 (the writer default) degrades gracefully',
  list?.[0]?.crimeType === 'All crime types', `crimeType=${list?.[0]?.crimeType}`);
check('a real crimesubheadid resolves to its label', list?.[1]?.crimeType === 'House Theft', `crimeType=${list?.[1]?.crimeType}`);
check('title carries the predicted count and district',
  /45 incidents predicted in Bengaluru Urban/.test(list?.[0]?.title ?? ''), `title=${list?.[0]?.title}`);
check('description adds the baseline comparison',
  /50% above the historical average/.test(list?.[0]?.description ?? ''), `desc=${(list?.[0]?.description ?? '').slice(0, 70)}`);
check('detectedAt comes from generatedat', list?.[0]?.detectedAt === '2026-07-26 10:00:00', `detectedAt=${list?.[0]?.detectedAt}`);

zcqlLog.length = 0;
res = await hit('GET', '/alerts/active?district=29');
check('?district= filters', res.body?.data?.length === 1 && res.body.data[0].district === 'Mysuru', `n=${res.body?.data?.length}`);

zcqlLog.length = 0;
res = await hit('GET', "/alerts/active?district=29' OR '1'='1");
check('district filter escapes quotes (no ZCQL injection)',
  res.status === 200 && !zcqlLog.some((q) => /OR '1'='1'/.test(q)), `status=${res.status}`);

console.log('\n=== QuickML forecast + RAG contracts ===\n');
console.log(checks.join('\n'));
console.log(`\n${failures === 0 ? 'ALL PASS' : `${failures} FAILURE(S)`}`);

process.exitCode = failures === 0 ? 0 : 1;
server.close();
